# Generated by Django 3.2.9 on 2021-12-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sum', models.IntegerField(blank=True, null=True, verbose_name='минимальная сумма')),
                ('max_sum', models.IntegerField(blank=True, null=True, verbose_name='максимальная сумма')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='старт приема заявок')),
                ('end_date', models.DateField(verbose_name='окончание приема заявок')),
                ('send_date', models.DateField(verbose_name='дата отправки подарков')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя Telegram')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_list', models.TextField(blank=True, verbose_name='список желаний')),
                ('santa_letter', models.TextField(blank=True, verbose_name='письмо Санте')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.game', verbose_name='игра')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='tgbot.user', verbose_name='получатель подарка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='пользователь')),
            ],
        ),
    ]
