# Generated by Django 3.2.9 on 2021-12-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_date',
        ),
    ]
