# Generated by Django 3.2.9 on 2021-12-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_game_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='название игры'),
            preserve_default=False,
        ),
    ]
