# Generated by Django 3.2.9 on 2021-12-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameparticipant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tgbot.game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tgbot.user', verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='ExcludePairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludepairs', to='tgbot.game', verbose_name='игра')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations1', to='tgbot.gameparticipant', verbose_name='первый участник')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations2', to='tgbot.gameparticipant', verbose_name='второй участник')),
            ],
        ),
    ]
