# Generated by Django 3.2.9 on 2021-12-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20211217_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludepairs',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_pairs', to='tgbot.game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='excludepairs',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_senders', to='tgbot.gameparticipant', verbose_name='Отправитель подарка'),
        ),
        migrations.AlterField(
            model_name='excludepairs',
            name='participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_recipients', to='tgbot.gameparticipant', verbose_name='Получатель подарка'),
        ),
    ]
