# Generated by Django 3.2.9 on 2021-12-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20211218_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludepairs',
            old_name='participant2',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='excludepairs',
            old_name='participant1',
            new_name='sender',
        ),
    ]
