# Generated by Django 3.2.9 on 2021-12-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20211218_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludepairs',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_pair_as_recipient', to='tgbot.gameparticipant', verbose_name='Получатель подарка'),
        ),
        migrations.AlterField(
            model_name='excludepairs',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_pair_as_sender', to='tgbot.gameparticipant', verbose_name='Отправитель подарка'),
        ),
    ]
