# Generated by Django 3.2.9 on 2021-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_auto_20211218_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='игра окончена'),
        ),
    ]
